/**
 * @file Swagger UI at /api/agent/swagger/, serving the committed openapi.json.
 *
 * Go's http-swagger served a spec generated by swag at the same path; this is
 * swagger-ui-express over the spec tsoa generates (openapi.json, copied into the image next to
 * dist/). Credentials are ignored: the header is never read and auth-service is never asked, so
 * the docs keep answering while it is down.
 *
 * Contract note 7 pins only reachability (the docs route answers 2xx or 3xx, ends in a 200
 * text/html page, the spec it loads is JSON, the centre is never asked), and the issue accepts that
 * http-swagger's redirect of the bare prefix and its 405 for HEAD are not reproduced. What stays
 * as it was: `/api/agent/swagger` WITHOUT the trailing slash is `404 page not found`, and only GET
 * and HEAD are served (a route answering every method with credentials ignored would be a
 * mutating route declaring nothing).
 */

import fs from "node:fs";
import path from "node:path";
import { passthrough, type ExpressAuth } from "@v-m-pioneer-trading/clerk-client";
import type { Express, RequestHandler } from "express";
import swaggerUi from "swagger-ui-express";
import { decodedPathOf, pageNotFound } from "./http/muxCompat";

export const SWAGGER_PATH = "/api/agent/swagger";

/** The static files of swagger-ui-dist the page references, and nothing else of that directory. */
export const ASSETS: ReadonlySet<string> = new Set([
  "/swagger-ui.css",
  "/swagger-ui-bundle.js",
  "/swagger-ui-standalone-preset.js",
  "/favicon-16x16.png",
  "/favicon-32x32.png",
]);

/** openapi.json: next to src/ in the tree, next to dist/ in the image. */
export const SPEC_FILE = path.join(__dirname, "..", "openapi.json");

let cached: object | undefined;
export function loadSpec(file: string = SPEC_FILE): object {
  if (file !== SPEC_FILE) return JSON.parse(fs.readFileSync(file, "utf8")) as object;
  cached ??= JSON.parse(fs.readFileSync(file, "utf8")) as object;
  return cached;
}

const TYPES: Readonly<Record<string, string>> = {
  ".css": "text/css; charset=UTF-8",
  ".js": "application/javascript; charset=UTF-8",
  ".png": "image/png",
};

/** The whitelisted files of swagger-ui-dist, in memory, by their path under the mount. */
// eslint-disable-next-line @typescript-eslint/no-require-imports -- swagger-ui-dist/absolute-path is a CommonJS module with no types or ESM entry; require is how it is loaded
export function loadAssets(dir: string = (require("swagger-ui-dist/absolute-path") as () => string)()): Map<string, { body: Buffer; type: string }> {
  return new Map([...ASSETS].map((name) => [name, { body: fs.readFileSync(path.join(dir, name)), type: TYPES[path.extname(name)] ?? "application/octet-stream" }]));
}

/** Mounts the UI on the app (which is secured(): the mount carries its declaration). */
export function mountSwagger(app: Express, auth: ExpressAuth, spec: object = loadSpec()): void {
  const page = swaggerUi.setup(spec, { customSiteTitle: "Agent Info Service API" });

  // Same answer as any path under /api/agent that no route takes.
  const refuse: RequestHandler = (_req, res) => { pageNotFound(res); };
  const gate: RequestHandler = (req, res, next) => {
    const bare = decodedPathOf(req).toString("latin1") === SWAGGER_PATH;
    if (bare || (req.method !== "GET" && req.method !== "HEAD")) refuse(req, res, next);
    else next();
  };
  // swagger-ui-dist's own index.html and swagger-initializer.js (the Petstore demo), README, LICENSE and the
  // package's .js files sit in the same directory: only the page and the files it references are served.
  const [initScript] = swaggerUi.serve as [RequestHandler, RequestHandler];
  // The assets are read once, here, and answered from memory: a file stream per request would hold a descriptor and
  // buffers for every response a pipelining caller never reads.
  const assets = loadAssets();
  const asset: RequestHandler = (req, res) => {
    const file = assets.get(req.path);
    if (file === undefined) {
      pageNotFound(res);
      return;
    }
    res.statusCode = 200;
    res.setHeader("Content-Type", file.type);
    res.setHeader("Content-Length", file.body.length);
    res.setHeader("Cache-Control", "public, max-age=0");
    res.end(req.method === "HEAD" ? undefined : file.body);
  };
  const docs: RequestHandler = (req, res, next) => {
    if (req.path === "/" || req.path === "/index.html") page(req, res, next);
    else if (req.path === "/swagger-ui-init.js") initScript(req, res, next);
    else if (ASSETS.has(req.path)) asset(req, res, next);
    else refuse(req, res, next);
  };

  // The gate comes first: a method the route does not serve is not a request for the declaration to judge.
  app.use(SWAGGER_PATH, passthrough(gate, "answers 404 to a method or a path the docs do not serve; serves no resource"), auth.ignoreCredentials(), docs);
}
