/**
 * @file Swagger UI at /api/agent/swagger/, serving the committed openapi.json.
 *
 * Go's http-swagger served a spec generated by swag at the same path; this is
 * swagger-ui-express over the spec tsoa generates (ts/openapi.json, copied into the image next to
 * dist/). Credentials are ignored: the header is never read and auth-service is never asked, so
 * the docs keep answering while it is down.
 *
 * Contract note 7 pins only reachability (the docs route answers 2xx or 3xx, ends in a 200
 * text/html page, the spec it loads is JSON, the centre is never asked), and the issue accepts that
 * http-swagger's redirect of the bare prefix and its 405 for HEAD are not reproduced. What stays
 * as it was: `/api/agent/swagger` WITHOUT the trailing slash is `404 page not found`, and only GET
 * and HEAD are served (a route answering every method with credentials ignored would be a
 * mutating route declaring nothing).
 */

import fs from "node:fs";
import path from "node:path";
import { passthrough, type ExpressAuth } from "@v-m-pioneer-trading/clerk-client";
import type { Express, RequestHandler } from "express";
import swaggerUi from "swagger-ui-express";
import { decodedPathOf, pageNotFound } from "./http/muxCompat";

export const SWAGGER_PATH = "/api/agent/swagger";

/** ts/openapi.json: next to src/ in the tree, next to dist/ in the image. */
export const SPEC_FILE = path.join(__dirname, "..", "openapi.json");

let cached: object | undefined;
export function loadSpec(file: string = SPEC_FILE): object {
  if (file !== SPEC_FILE) return JSON.parse(fs.readFileSync(file, "utf8")) as object;
  cached ??= JSON.parse(fs.readFileSync(file, "utf8")) as object;
  return cached;
}

/** Mounts the UI on the app (which is secured(): the mount carries its declaration). */
export function mountSwagger(app: Express, auth: ExpressAuth, spec: object = loadSpec()): void {
  const page = swaggerUi.setup(spec, { customSiteTitle: "Agent Info Service API" });

  // Same answer as any path under /api/agent that no route takes.
  const refuse: RequestHandler = (_req, res) => pageNotFound(res);
  const gate: RequestHandler = (req, res, next) => {
    const bare = decodedPathOf(req).toString("latin1") === SWAGGER_PATH;
    if (bare || (req.method !== "GET" && req.method !== "HEAD")) refuse(req, res, next);
    else next();
  };
  // setup() answers with the page on any path that reaches it; only the page's own two names should.
  const index: RequestHandler = (req, res, next) => (req.path === "/" || req.path === "/index.html" ? page(req, res, next) : refuse(req, res, next));

  // The gate comes first: a method the route does not serve is not a request for the declaration to judge.
  app.use(SWAGGER_PATH, passthrough(gate, "answers 404 to a method or a path the docs do not serve; serves no resource"), auth.ignoreCredentials(), ...swaggerUi.serve, index);
}
